### PR TITLE
Fixes iOS 18+ runtime downloads

### LINKED ISSUE #384: iOS 18 runtime can not be downloaded
➜ xcodes runtimes download "iOS 18.0"
Error: Runtime com.apple.dmg.iPhoneSimulatorSDK18_0 is missing source url. Downloading of iOS 18 runtimes are not supported. Please install manually see https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtime

### PR DESCRIPTION
**Pull request by spadafiva**
This PR attempts to port the logic from https://github.com/XcodesOrg/XcodesApp/pull/622 to the CLI tool.

Fixes #384 

The logic in the `downloadAndInstallRuntime` was modified to now switch over the runtime's content type.  The previous existing package and disk image installs were left unchanged, but the `.cryptexDiskImage` case is now handled by the `downloadAndInstallUsingXcodeBuild` function.

This function does 3 main things (broken into some smaller helper functions for those).
1. Check that we're using a new enough version of Xcode
2. Start downloading using Xcodebuild and create an AsyncStream of the progress
3. Write out that progress to the console

## Testing:
In order to test this out you will need to have xcode 16.1 or newer installed.  

Things I tested and seemed to work for me:
1. try to install a runtime with the correct xcode selected
2. try to install a cryptex runtime with a too low version selected

# Caveats:
I'm not sure what happens to the underlying xcodebuild install process if you cancel the command from the terminal with CMD+C.

When the selected runtime is already installed, the tool will still go through the download process but complete quickly:

```
[1A[KDownloading Runtime iOS 18.1: 0%
[1A[KDownloading Runtime iOS 18.1: 0%
[1A[KDownloading Runtime iOS 18.1: 0%
[1A[KDownloading Runtime iOS 18.1: 0%
Finished
```

It might be worth following up in a future PR to check if the runtime is actually already installed instead of doing this.

### CODE REVIEW

File: Sources/XcodesKit/RuntimeInstaller.swift [hunk 1]
```diff
@@ -294,3 +408,39 @@ extension Array {
         return result
     }
 }
+
+
+private extension Progress {
+    func updateFromXcodebuild(text: String) {
```
Comment (spadafiva) [inline Sources/XcodesKit/RuntimeInstaller.swift:414]: Taken directly from the other PR

File: Sources/XcodesKit/RuntimeInstaller.swift [hunk 2]
```diff
@@ -224,6 +217,124 @@ public class RuntimeInstaller {
...
+
+    // Creates and invokes the xcodebuild install command and converts it to a stream of Progress
+    private func createXcodebuildDownloadStream(runtime: DownloadableRuntime) -> AsyncThrowingStream<Progress, Swift.Error> {
+        let platform = runtime.platform.shortName
+        let version = runtime.simulatorVersion.buildUpdate
+
+        return AsyncThrowingStream<Progress, Swift.Error> { continuation in
+            Task {
+                // Assume progress will not have data races, so we manually opt-out isolation checks.
+                let progress = Progress()
```
Comment (spadafiva) [inline Sources/XcodesKit/RuntimeInstaller.swift:273]: More or less verbatim from the other PR

**Comment by spadafiva** [comment]
@MattKiazyk guessing you’re busy with other work stuff, just wanted to bump this in case it got lost in the shuffle. Let me know if there’s anything else I can do

**Comment by MattKiazyk** [comment]
@spadafiva sorry was trying to get login back up and working first. I'll look at this right away. Ok if I make any changes to your PR needed and just merge?

**Comment by spadafiva** [comment]
> @spadafiva sorry was trying to get login back up and working first. I'll look at this right away. Ok if I make any changes to your PR needed and just merge?

Sounds great!  Thanks!  Also, if there's anything I can to do help with the login stuff, would love to help out if I can.

**Comment by MattKiazyk** [comment]
> > @spadafiva sorry was trying to get login back up and working first. I'll look at this right away. Ok if I make any changes to your PR needed and just merge?
> 
> Sounds great! Thanks! Also, if there's anything I can to do help with the login stuff, would love to help out if I can.

PR https://github.com/XcodesOrg/xcodes/pull/393 is up that includes it, if you'd like to test.

**Comment by spadafiva** [comment]
Also, @MattKiazyk, just in case it's not clear, thanks so much for maintaining the very useful tool.  Me (and the the rest of the team) definitely appreciate how useful it is and the hard work you've put into maintaining it.

**Comment by ugenlik** [comment]
@MattKiazyk  could you add documentation on how to download runtimes, I am trying to automated a CLI pipeline and I want to download runtimes first before installing it

when I try  this I get 
```
xcodes runtimes download "iOS 18.1"
Error: Downloading runtime iOS 18.1 is not supported at this time. Please use `xcodes runtimes install "iOS 18.1"` instead.
```

why does it need to check if xcode installed first, I am just trying to download the package, otherwise I would have used install command

**Comment by spadafiva** [comment]
> @MattKiazyk could you add documentation on how to download runtimes, I am trying to automated a CLI pipeline and I want to download runtimes first before installing it
> 
> when I try this I get
> 
> ```
> xcodes runtimes download "iOS 18.1"
> Error: Downloading runtime iOS 18.1 is not supported at this time. Please use `xcodes runtimes install "iOS 18.1"` instead.
> ```
> 
> why does it need to check if xcode installed first, I am just trying to download the package, otherwise I would have used install command

iOS 18.1 can't be ** just downloaded ** since it relies on the built in xcodebuild command now due to the changes on apple's side.  So you can only `install`, it's not possible to download without installing.

**Comment by MattKiazyk** [comment]
To clarify - Xcodes currently only wraps the install command of `xcodebuild` 

There is a `xcodebuild -exportPath` command available to export the runtime, but xcodes hasn't implemented that yet.
